/Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>655</Iteration_iter-num>
      <Iteration_query-ID>Query_655</Iteration_query-ID>
      <Iteration_query-def>@s122330_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>100</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>4</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>656</Iteration_iter-num>
      <Iteration_query-ID>Query_656</Iteration_query-ID>
      <Iteration_query-def>@s123027_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>111</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>6</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>657</Iteration_iter-num>
      <Iteration_query-ID>Query_657</Iteration_query-ID>
      <Iteration_query-def>@s123856_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>249</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>18</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>658</Iteration_iter-num>
      <Iteration_query-ID>Query_658</Iteration_query-ID>
      <Iteration_query-def>@s124163_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>249</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>18</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>659</Iteration_iter-num>
      <Iteration_query-ID>Query_659</Iteration_query-ID>
      <Iteration_query-def>@s124665_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>171</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>13</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>660</Iteration_iter-num>
      <Iteration_query-ID>Query_660</Iteration_query-ID>
      <Iteration_query-def>@s125124_2_CDC5B</Iteration_query-def>
      <Iteration_query-len>234</Iteration_query-len>
      <Iteration_hits></Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>326629</Statistics_db-num>
          <Statistics_db-len>122844229</Statistics_db-len>
          <Statistics_hsp-len>18</Statistics_hsp-len>
          <Statistics_eff-space>1000000000</Statistics_eff-space>
          <Statistics_kappa>0.041</Statistics_kappa>
          <Statistics_lambda>0.267</Statistics_lambda>
          <Statistics_entropy>0.14</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
      <Iteration_message>No hits found</Iteration_message>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>661</Iteration_iter-num>
      <Iteration_query-ID>Query_661</Iteration_query-ID>
      <Iteration_query-de